INSERT INTO unitmeasure(id, name, symbol, version) VALUES (1, 'Unit', 'nr', 0)
INSERT INTO unitmeasure(id, name, symbol, version) VALUES (2, 'Meter', 'm', 0)
INSERT INTO unitmeasure(id, name, symbol, version) VALUES (3, 'Liter', 'l', 0)
INSERT INTO internalelement(id, name, version) VALUES (1, 'Design', 0)
INSERT INTO internalelement(id, name, version) VALUES (2, 'Developement', 0)
INSERT INTO internalelement(id, name, version) VALUES (3, 'Consulting', 0)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (1, 'item001', 'Normal item', 4.15, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (2, 'item002', 'Blue item', 2, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (3, 'item003', 'Red item', 2.1, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (4, 'item004', 'Water', 10, 0, 3)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (5, 'item005', 'Large and thin wook', 42.5, 0, 2)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (1, 'grp', null, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (1, 'Test root node')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (2, 'grp', 1, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (2, 'Child 0.0')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (3, 'grp', 1, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (3, 'Child 0.1')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (4, 'grp', 1, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (4, 'Child 0.2')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (5, 'grp', 2, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (5, 'Child 0.0.0')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (6, 'grp', 2, 1, 1, 0)
INSERT INTO groupnode(id, description) VALUES (6, 'Child 0.0.1')
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (7, 'int', 3, 1, 1, 0)
INSERT INTO internalnode(id, element_id) VALUES (7, 1)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (8, 'int', 3, 1, 1, 0)
INSERT INTO internalnode(id, element_id) VALUES (8, 2)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (9, 'int', 3, 1, 1, 0)
INSERT INTO internalnode(id, element_id) VALUES (9, 3)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (10, 'ext', 4, 1, 1, 0)
INSERT INTO externalnode(id, element_id) VALUES (10, 1)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (11, 'ext', 4, 1, 1, 0)
INSERT INTO externalnode(id, element_id) VALUES (11, 2)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (12, 'ext', 4, 1, 1, 0)
INSERT INTO externalnode(id, element_id) VALUES (12, 3)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (13, 'ext', 4, 1, 1, 0)
INSERT INTO externalnode(id, element_id) VALUES (13, 4)
INSERT INTO node(id, dtype, father_id, price, qty, version) VALUES (14, 'ext', 4, 1, 1, 0)
INSERT INTO externalnode(id, element_id) VALUES (14, 5)
INSERT INTO tree(id, name, version, root_id) VALUES (1, 'Test tree', 0, 1)
