INSERT INTO unitmeasure(id, name, symbol, version) VALUES (1, 'Unit', 'nr', 0)
INSERT INTO unitmeasure(id, name, symbol, version) VALUES (2, 'Meter', 'm', 0)
INSERT INTO unitmeasure(id, name, symbol, version) VALUES (3, 'Liter', 'l', 0)
INSERT INTO internalelement(id, name, version) VALUES (1, 'Design', 0)
INSERT INTO internalelement(id, name, version) VALUES (2, 'Developement', 0)
INSERT INTO internalelement(id, name, version) VALUES (3, 'Consulting', 0)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (1, 'item001', 'Normal item', 4.15, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (2, 'item002', 'Blue item', 2, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (3, 'item003', 'Red item', 2.1, 0, 1)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (4, 'item004', 'Water', 10, 0, 3)
INSERT INTO externalelement(id, code, description, price, version, um_id) VALUES (5, 'item005', 'Large and thin wook', 42.5, 0, 2)
